name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '8.0'
          distribution: 'temurin'

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          prerelease: false
          tag_name: "v1.0.${{ github.run_number }}"
          name: "Release v1.0.${{ github.run_number }}"